
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox bigBox;

	private global::Gtk.VBox leftSideBox;

	private global::Gtk.ScrolledWindow scrolledwindow4;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.VBox newPodBox;

	private global::Gtk.HBox labelBox;

	private global::Gtk.Label choseURLLabel;

	private global::Gtk.Label choseUppdateringsfrekvensLabel;

	private global::Gtk.Label choseKategoriLabel;

	private global::Gtk.HBox hbox26;

	private global::Gtk.Entry entry8;

	private global::Gtk.ComboBox combobox5;

	private global::Gtk.ComboBox combobox7;

	private global::Gtk.HBox hbox24;

	private global::Gtk.Fixed fixed13;

	private global::Gtk.HBox leftButtonBox;

	private global::Gtk.Button leftNewButton;

	private global::Gtk.Button leftSaveButton;

	private global::Gtk.Button leftRemoveButton;

	private global::Gtk.VBox vbox25;

	private global::Gtk.Label podcastLabel;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.TextView textview7;

	private global::Gtk.VBox vbox13;

	private global::Gtk.VBox vbox15;

	private global::Gtk.Label kategoriLabel;

	private global::Gtk.VBox vbox17;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview6;

	private global::Gtk.Entry entry6;

	private global::Gtk.VBox vbox19;

	private global::Gtk.HBox rightButtonBox;

	private global::Gtk.Button rightNewButton;

	private global::Gtk.Button rightSaveButton;

	private global::Gtk.Button rightRemoveButton;

	private global::Gtk.Label avsnittsLabel;

	private global::Gtk.ScrolledWindow episodeInfoScrolledWindow;

	private global::Gtk.TextView episodeInfoTextview;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(25));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.bigBox = new global::Gtk.HBox();
		this.bigBox.Name = "bigBox";
		this.bigBox.Spacing = 6;
		// Container child bigBox.Gtk.Box+BoxChild
		this.leftSideBox = new global::Gtk.VBox();
		this.leftSideBox.Name = "leftSideBox";
		this.leftSideBox.Spacing = 6;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.scrolledwindow4 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow4.CanFocus = true;
		this.scrolledwindow4.Name = "scrolledwindow4";
		this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow4.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.scrolledwindow4.Add(this.nodeview1);
		this.leftSideBox.Add(this.scrolledwindow4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.scrolledwindow4]));
		w2.Position = 0;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.newPodBox = new global::Gtk.VBox();
		this.newPodBox.Name = "newPodBox";
		this.newPodBox.Spacing = 6;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.labelBox = new global::Gtk.HBox();
		this.labelBox.Name = "labelBox";
		this.labelBox.Spacing = 6;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseURLLabel = new global::Gtk.Label();
		this.choseURLLabel.WidthRequest = 235;
		this.choseURLLabel.Name = "choseURLLabel";
		this.choseURLLabel.Xalign = 0F;
		this.choseURLLabel.LabelProp = global::Mono.Unix.Catalog.GetString("URL:");
		this.labelBox.Add(this.choseURLLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseURLLabel]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseUppdateringsfrekvensLabel = new global::Gtk.Label();
		this.choseUppdateringsfrekvensLabel.WidthRequest = 127;
		this.choseUppdateringsfrekvensLabel.Name = "choseUppdateringsfrekvensLabel";
		this.choseUppdateringsfrekvensLabel.Xalign = 0F;
		this.choseUppdateringsfrekvensLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Uppdateringsfrekvens:");
		this.labelBox.Add(this.choseUppdateringsfrekvensLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseUppdateringsfrekvensLabel]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseKategoriLabel = new global::Gtk.Label();
		this.choseKategoriLabel.WidthRequest = 122;
		this.choseKategoriLabel.Name = "choseKategoriLabel";
		this.choseKategoriLabel.Xalign = 0F;
		this.choseKategoriLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Kategori:");
		this.labelBox.Add(this.choseKategoriLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseKategoriLabel]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.newPodBox.Add(this.labelBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.labelBox]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox();
		this.hbox26.Name = "hbox26";
		this.hbox26.Spacing = 6;
		// Container child hbox26.Gtk.Box+BoxChild
		this.entry8 = new global::Gtk.Entry();
		this.entry8.WidthRequest = 100;
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.Text = global::Mono.Unix.Catalog.GetString("http://...");
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '●';
		this.hbox26.Add(this.entry8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.entry8]));
		w7.Position = 0;
		// Container child hbox26.Gtk.Box+BoxChild
		this.combobox5 = global::Gtk.ComboBox.NewText();
		this.combobox5.WidthRequest = 125;
		this.combobox5.Name = "combobox5";
		this.hbox26.Add(this.combobox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.combobox5]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox26.Gtk.Box+BoxChild
		this.combobox7 = global::Gtk.ComboBox.NewText();
		this.combobox7.WidthRequest = 125;
		this.combobox7.Name = "combobox7";
		this.hbox26.Add(this.combobox7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.combobox7]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.newPodBox.Add(this.hbox26);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.hbox26]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.hbox24 = new global::Gtk.HBox();
		this.hbox24.Name = "hbox24";
		this.hbox24.Spacing = 6;
		// Container child hbox24.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed();
		this.fixed13.WidthRequest = 100;
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.hbox24.Add(this.fixed13);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.fixed13]));
		w11.Position = 0;
		// Container child hbox24.Gtk.Box+BoxChild
		this.leftButtonBox = new global::Gtk.HBox();
		this.leftButtonBox.Name = "leftButtonBox";
		this.leftButtonBox.Spacing = 6;
		// Container child leftButtonBox.Gtk.Box+BoxChild
		this.leftNewButton = new global::Gtk.Button();
		this.leftNewButton.CanFocus = true;
		this.leftNewButton.Name = "leftNewButton";
		this.leftNewButton.UseUnderline = true;
		this.leftNewButton.Label = global::Mono.Unix.Catalog.GetString("Ny...");
		this.leftButtonBox.Add(this.leftNewButton);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.leftButtonBox[this.leftNewButton]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child leftButtonBox.Gtk.Box+BoxChild
		this.leftSaveButton = new global::Gtk.Button();
		this.leftSaveButton.CanFocus = true;
		this.leftSaveButton.Name = "leftSaveButton";
		this.leftSaveButton.UseUnderline = true;
		this.leftSaveButton.Label = global::Mono.Unix.Catalog.GetString("Spara");
		this.leftButtonBox.Add(this.leftSaveButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.leftButtonBox[this.leftSaveButton]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child leftButtonBox.Gtk.Box+BoxChild
		this.leftRemoveButton = new global::Gtk.Button();
		this.leftRemoveButton.CanFocus = true;
		this.leftRemoveButton.Name = "leftRemoveButton";
		this.leftRemoveButton.UseUnderline = true;
		this.leftRemoveButton.Label = global::Mono.Unix.Catalog.GetString("Ta Bort...");
		this.leftButtonBox.Add(this.leftRemoveButton);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.leftButtonBox[this.leftRemoveButton]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.hbox24.Add(this.leftButtonBox);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.leftButtonBox]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.newPodBox.Add(this.hbox24);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.hbox24]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.leftSideBox.Add(this.newPodBox);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.newPodBox]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.vbox25 = new global::Gtk.VBox();
		this.vbox25.Name = "vbox25";
		this.vbox25.Spacing = 6;
		// Container child vbox25.Gtk.Box+BoxChild
		this.podcastLabel = new global::Gtk.Label();
		this.podcastLabel.WidthRequest = 500;
		this.podcastLabel.Name = "podcastLabel";
		this.podcastLabel.Xalign = 0F;
		this.podcastLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Namn på podcast");
		this.vbox25.Add(this.podcastLabel);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.podcastLabel]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox25.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.textview7 = new global::Gtk.TextView();
		this.textview7.CanFocus = true;
		this.textview7.Name = "textview7";
		this.textview7.Editable = false;
		this.scrolledwindow2.Add(this.textview7);
		this.vbox25.Add(this.scrolledwindow2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.scrolledwindow2]));
		w20.Position = 1;
		this.leftSideBox.Add(this.vbox25);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.vbox25]));
		w21.Position = 2;
		this.bigBox.Add(this.leftSideBox);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.bigBox[this.leftSideBox]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child bigBox.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.kategoriLabel = new global::Gtk.Label();
		this.kategoriLabel.Name = "kategoriLabel";
		this.kategoriLabel.Xalign = 0F;
		this.kategoriLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorier:");
		this.vbox15.Add(this.kategoriLabel);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.kategoriLabel]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox13.Add(this.vbox15);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox15]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox17 = new global::Gtk.VBox();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview6 = new global::Gtk.TextView();
		this.textview6.CanFocus = true;
		this.textview6.Name = "textview6";
		this.textview6.Editable = false;
		this.GtkScrolledWindow1.Add(this.textview6);
		this.vbox17.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.GtkScrolledWindow1]));
		w26.Position = 0;
		// Container child vbox17.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.vbox17.Add(this.entry6);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.entry6]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox13.Add(this.vbox17);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox17]));
		w28.Position = 1;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox19 = new global::Gtk.VBox();
		this.vbox19.Name = "vbox19";
		this.vbox19.Spacing = 6;
		// Container child vbox19.Gtk.Box+BoxChild
		this.rightButtonBox = new global::Gtk.HBox();
		this.rightButtonBox.Name = "rightButtonBox";
		this.rightButtonBox.Spacing = 6;
		// Container child rightButtonBox.Gtk.Box+BoxChild
		this.rightNewButton = new global::Gtk.Button();
		this.rightNewButton.CanFocus = true;
		this.rightNewButton.Name = "rightNewButton";
		this.rightNewButton.UseUnderline = true;
		this.rightNewButton.Label = global::Mono.Unix.Catalog.GetString("Ny...");
		this.rightButtonBox.Add(this.rightNewButton);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.rightButtonBox[this.rightNewButton]));
		w29.Position = 0;
		w29.Fill = false;
		// Container child rightButtonBox.Gtk.Box+BoxChild
		this.rightSaveButton = new global::Gtk.Button();
		this.rightSaveButton.CanFocus = true;
		this.rightSaveButton.Name = "rightSaveButton";
		this.rightSaveButton.UseUnderline = true;
		this.rightSaveButton.Label = global::Mono.Unix.Catalog.GetString("Spara");
		this.rightButtonBox.Add(this.rightSaveButton);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.rightButtonBox[this.rightSaveButton]));
		w30.Position = 1;
		w30.Fill = false;
		// Container child rightButtonBox.Gtk.Box+BoxChild
		this.rightRemoveButton = new global::Gtk.Button();
		this.rightRemoveButton.CanFocus = true;
		this.rightRemoveButton.Name = "rightRemoveButton";
		this.rightRemoveButton.UseUnderline = true;
		this.rightRemoveButton.Label = global::Mono.Unix.Catalog.GetString("Ta Bort...");
		this.rightButtonBox.Add(this.rightRemoveButton);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.rightButtonBox[this.rightRemoveButton]));
		w31.Position = 2;
		w31.Fill = false;
		this.vbox19.Add(this.rightButtonBox);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.rightButtonBox]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.avsnittsLabel = new global::Gtk.Label();
		this.avsnittsLabel.WidthRequest = 300;
		this.avsnittsLabel.Name = "avsnittsLabel";
		this.avsnittsLabel.Xalign = 0F;
		this.avsnittsLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Namn på podcast och avsnitt");
		this.vbox19.Add(this.avsnittsLabel);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.avsnittsLabel]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.episodeInfoScrolledWindow = new global::Gtk.ScrolledWindow();
		this.episodeInfoScrolledWindow.Name = "episodeInfoScrolledWindow";
		this.episodeInfoScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child episodeInfoScrolledWindow.Gtk.Container+ContainerChild
		this.episodeInfoTextview = new global::Gtk.TextView();
		this.episodeInfoTextview.CanFocus = true;
		this.episodeInfoTextview.Name = "episodeInfoTextview";
		this.episodeInfoTextview.Editable = false;
		this.episodeInfoScrolledWindow.Add(this.episodeInfoTextview);
		this.vbox19.Add(this.episodeInfoScrolledWindow);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.episodeInfoScrolledWindow]));
		w35.Position = 2;
		this.vbox13.Add(this.vbox19);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox19]));
		w36.Position = 2;
		this.bigBox.Add(this.vbox13);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.bigBox[this.vbox13]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.Add(this.bigBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 860;
		this.DefaultHeight = 427;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
