
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox bigBox;

	private global::Gtk.VBox leftSideBox;

	private global::Gtk.ScrolledWindow scrolledwindow4;

	private global::Gtk.TreeView treeviewPodcast;

	private global::Gtk.VBox newPodBox;

	private global::Gtk.HBox labelBox;

	private global::Gtk.Label choseURLLabel;

	private global::Gtk.Label choseUppdateringsfrekvensLabel;

	private global::Gtk.Label choseKategoriLabel;

	private global::Gtk.HBox hbox26;

	private global::Gtk.Entry entryURL;

	private global::Gtk.ComboBox comboboxFrekvens;

	private global::Gtk.ComboBox comboboxKategori;

	private global::Gtk.HBox hbox24;

	private global::Gtk.Fixed fixed13;

	private global::Gtk.HBox leftButtonBox;

	private global::Gtk.Button leftSaveButton;

	private global::Gtk.Button leftRemoveButton;

	private global::Gtk.VBox vbox25;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.TreeView treeviewAvsnitt;

	private global::Gtk.VBox vbox13;

	private global::Gtk.VBox vbox17;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeviewKategorier;

	private global::Gtk.Entry entryKategori;

	private global::Gtk.VBox vbox19;

	private global::Gtk.HBox rightButtonBox;

	private global::Gtk.Button rightSaveButton;

	private global::Gtk.Button rightRemoveButton;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textviewAvsnitt;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(25));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.bigBox = new global::Gtk.HBox();
		this.bigBox.Name = "bigBox";
		this.bigBox.Spacing = 6;
		// Container child bigBox.Gtk.Box+BoxChild
		this.leftSideBox = new global::Gtk.VBox();
		this.leftSideBox.Name = "leftSideBox";
		this.leftSideBox.Spacing = 6;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.scrolledwindow4 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow4.CanFocus = true;
		this.scrolledwindow4.Name = "scrolledwindow4";
		this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow4.Gtk.Container+ContainerChild
		this.treeviewPodcast = new global::Gtk.TreeView();
		this.treeviewPodcast.CanFocus = true;
		this.treeviewPodcast.Name = "treeviewPodcast";
		this.scrolledwindow4.Add(this.treeviewPodcast);
		this.leftSideBox.Add(this.scrolledwindow4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.scrolledwindow4]));
		w2.Position = 0;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.newPodBox = new global::Gtk.VBox();
		this.newPodBox.Name = "newPodBox";
		this.newPodBox.Spacing = 6;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.labelBox = new global::Gtk.HBox();
		this.labelBox.Name = "labelBox";
		this.labelBox.Spacing = 6;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseURLLabel = new global::Gtk.Label();
		this.choseURLLabel.WidthRequest = 235;
		this.choseURLLabel.Name = "choseURLLabel";
		this.choseURLLabel.Xalign = 0F;
		this.choseURLLabel.LabelProp = global::Mono.Unix.Catalog.GetString("URL:");
		this.labelBox.Add(this.choseURLLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseURLLabel]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseUppdateringsfrekvensLabel = new global::Gtk.Label();
		this.choseUppdateringsfrekvensLabel.WidthRequest = 127;
		this.choseUppdateringsfrekvensLabel.Name = "choseUppdateringsfrekvensLabel";
		this.choseUppdateringsfrekvensLabel.Xalign = 0F;
		this.choseUppdateringsfrekvensLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Uppdateringsfrekvens:");
		this.labelBox.Add(this.choseUppdateringsfrekvensLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseUppdateringsfrekvensLabel]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child labelBox.Gtk.Box+BoxChild
		this.choseKategoriLabel = new global::Gtk.Label();
		this.choseKategoriLabel.WidthRequest = 122;
		this.choseKategoriLabel.Name = "choseKategoriLabel";
		this.choseKategoriLabel.Xalign = 0F;
		this.choseKategoriLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Kategori:");
		this.labelBox.Add(this.choseKategoriLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.labelBox[this.choseKategoriLabel]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.newPodBox.Add(this.labelBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.labelBox]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox();
		this.hbox26.Name = "hbox26";
		this.hbox26.Spacing = 6;
		// Container child hbox26.Gtk.Box+BoxChild
		this.entryURL = new global::Gtk.Entry();
		this.entryURL.WidthRequest = 100;
		this.entryURL.CanFocus = true;
		this.entryURL.Name = "entryURL";
		this.entryURL.Text = global::Mono.Unix.Catalog.GetString("http://...");
		this.entryURL.IsEditable = true;
		this.entryURL.InvisibleChar = '●';
		this.hbox26.Add(this.entryURL);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.entryURL]));
		w7.Position = 0;
		// Container child hbox26.Gtk.Box+BoxChild
		this.comboboxFrekvens = global::Gtk.ComboBox.NewText();
		this.comboboxFrekvens.WidthRequest = 125;
		this.comboboxFrekvens.Name = "comboboxFrekvens";
		this.hbox26.Add(this.comboboxFrekvens);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.comboboxFrekvens]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox26.Gtk.Box+BoxChild
		this.comboboxKategori = global::Gtk.ComboBox.NewText();
		this.comboboxKategori.WidthRequest = 125;
		this.comboboxKategori.Name = "comboboxKategori";
		this.hbox26.Add(this.comboboxKategori);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.comboboxKategori]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.newPodBox.Add(this.hbox26);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.hbox26]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child newPodBox.Gtk.Box+BoxChild
		this.hbox24 = new global::Gtk.HBox();
		this.hbox24.Name = "hbox24";
		this.hbox24.Spacing = 6;
		// Container child hbox24.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed();
		this.fixed13.WidthRequest = 100;
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.hbox24.Add(this.fixed13);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.fixed13]));
		w11.Position = 0;
		// Container child hbox24.Gtk.Box+BoxChild
		this.leftButtonBox = new global::Gtk.HBox();
		this.leftButtonBox.Name = "leftButtonBox";
		this.leftButtonBox.Spacing = 6;
		// Container child leftButtonBox.Gtk.Box+BoxChild
		this.leftSaveButton = new global::Gtk.Button();
		this.leftSaveButton.CanFocus = true;
		this.leftSaveButton.Name = "leftSaveButton";
		this.leftSaveButton.UseUnderline = true;
		this.leftSaveButton.Label = global::Mono.Unix.Catalog.GetString("Spara");
		this.leftButtonBox.Add(this.leftSaveButton);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.leftButtonBox[this.leftSaveButton]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child leftButtonBox.Gtk.Box+BoxChild
		this.leftRemoveButton = new global::Gtk.Button();
		this.leftRemoveButton.CanFocus = true;
		this.leftRemoveButton.Name = "leftRemoveButton";
		this.leftRemoveButton.UseUnderline = true;
		this.leftRemoveButton.Label = global::Mono.Unix.Catalog.GetString("Ta Bort...");
		this.leftButtonBox.Add(this.leftRemoveButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.leftButtonBox[this.leftRemoveButton]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox24.Add(this.leftButtonBox);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.leftButtonBox]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.newPodBox.Add(this.hbox24);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.newPodBox[this.hbox24]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.leftSideBox.Add(this.newPodBox);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.newPodBox]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child leftSideBox.Gtk.Box+BoxChild
		this.vbox25 = new global::Gtk.VBox();
		this.vbox25.Name = "vbox25";
		this.vbox25.Spacing = 6;
		// Container child vbox25.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.treeviewAvsnitt = new global::Gtk.TreeView();
		this.treeviewAvsnitt.CanFocus = true;
		this.treeviewAvsnitt.Events = ((global::Gdk.EventMask)(20));
		this.treeviewAvsnitt.Name = "treeviewAvsnitt";
		this.scrolledwindow2.Add(this.treeviewAvsnitt);
		this.vbox25.Add(this.scrolledwindow2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.scrolledwindow2]));
		w18.Position = 0;
		this.leftSideBox.Add(this.vbox25);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.leftSideBox[this.vbox25]));
		w19.Position = 2;
		this.bigBox.Add(this.leftSideBox);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.bigBox[this.leftSideBox]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child bigBox.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox17 = new global::Gtk.VBox();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewKategorier = new global::Gtk.TreeView();
		this.treeviewKategorier.CanFocus = true;
		this.treeviewKategorier.Events = ((global::Gdk.EventMask)(278));
		this.treeviewKategorier.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.treeviewKategorier.Name = "treeviewKategorier";
		this.treeviewKategorier.SearchColumn = 0;
		this.GtkScrolledWindow.Add(this.treeviewKategorier);
		this.vbox17.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.GtkScrolledWindow]));
		w22.Position = 0;
		// Container child vbox17.Gtk.Box+BoxChild
		this.entryKategori = new global::Gtk.Entry();
		this.entryKategori.WidthRequest = 300;
		this.entryKategori.CanFocus = true;
		this.entryKategori.Name = "entryKategori";
		this.entryKategori.IsEditable = true;
		this.entryKategori.InvisibleChar = '●';
		this.vbox17.Add(this.entryKategori);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.entryKategori]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox13.Add(this.vbox17);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox17]));
		w24.Position = 0;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox19 = new global::Gtk.VBox();
		this.vbox19.Name = "vbox19";
		this.vbox19.Spacing = 6;
		// Container child vbox19.Gtk.Box+BoxChild
		this.rightButtonBox = new global::Gtk.HBox();
		this.rightButtonBox.Name = "rightButtonBox";
		this.rightButtonBox.Spacing = 6;
		// Container child rightButtonBox.Gtk.Box+BoxChild
		this.rightSaveButton = new global::Gtk.Button();
		this.rightSaveButton.CanFocus = true;
		this.rightSaveButton.Name = "rightSaveButton";
		this.rightSaveButton.UseUnderline = true;
		this.rightSaveButton.Label = global::Mono.Unix.Catalog.GetString("Spara");
		this.rightButtonBox.Add(this.rightSaveButton);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.rightButtonBox[this.rightSaveButton]));
		w25.Position = 0;
		w25.Fill = false;
		// Container child rightButtonBox.Gtk.Box+BoxChild
		this.rightRemoveButton = new global::Gtk.Button();
		this.rightRemoveButton.CanFocus = true;
		this.rightRemoveButton.Name = "rightRemoveButton";
		this.rightRemoveButton.UseUnderline = true;
		this.rightRemoveButton.Label = global::Mono.Unix.Catalog.GetString("Ta Bort...");
		this.rightButtonBox.Add(this.rightRemoveButton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.rightButtonBox[this.rightRemoveButton]));
		w26.Position = 1;
		w26.Fill = false;
		this.vbox19.Add(this.rightButtonBox);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.rightButtonBox]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Podcast #1 - Avsnitt #3");
		this.vbox19.Add(this.label1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label1]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewAvsnitt = new global::Gtk.TextView();
		this.textviewAvsnitt.CanFocus = true;
		this.textviewAvsnitt.Name = "textviewAvsnitt";
		this.GtkScrolledWindow1.Add(this.textviewAvsnitt);
		this.vbox19.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.GtkScrolledWindow1]));
		w30.Position = 2;
		this.vbox13.Add(this.vbox19);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox19]));
		w31.Position = 1;
		this.bigBox.Add(this.vbox13);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.bigBox[this.vbox13]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		this.Add(this.bigBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 877;
		this.DefaultHeight = 427;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.treeviewPodcast.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeviewPodcastRowActivated);
		this.leftSaveButton.Clicked += new global::System.EventHandler(this.AddPodFeed);
		this.leftRemoveButton.Clicked += new global::System.EventHandler(this.RemovePodcast);
		this.treeviewAvsnitt.RowActivated += new global::Gtk.RowActivatedHandler(this.ShowDescription);
		this.treeviewKategorier.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeviewKategorierRowActivated);
		this.rightSaveButton.Clicked += new global::System.EventHandler(this.AddKategori);
		this.rightRemoveButton.Clicked += new global::System.EventHandler(this.RemoveKategori);
	}
}
